version: '3'

services:
  mongodb:
        image: mongo
        ports:
          - 27017:27017
  api:
        image: vitta/nodemon
        ports:
          - 4000:4000
        working_dir: /api
        volumes:
          - ./:/api
        depends_on:
          - mongodb
        command: 'npm start'
        environment:
          - MONGODB_URI=mongodb://mongodb/seca-sample
