version: '3'

services:
  mongodb:
        image: mongo
        ports:
          - 27017:27017
  api:
        image: vitta/nodemon
        ports:
          - 4000:4000
        working_dir: /api
        volumes:
          - ./:/api
        depends_on:
          - mongodb
        command: npm run dev
        environment:
          - MONGODB_URI=mongodb://mongodb/seca-sample
  ui:
        image: johnpapa/angular-cli
        ports:
          - 4200:4200
        working_dir: /ui
        volumes:
          - ./ui:/ui
        depends_on:
          - api
        command: 'ng serve'
